name: Semantic Release on Merge
on:
  push:
    branches:
      - 'master'
      - 'main'
jobs:
  release:
    name: Attempt Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.10
      - name: Install
        run: npm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
      - name: Add remote SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DRUPAL_ORG_SSH_KEY }}
          config: ${{ secrets.SSH_CONFIG }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Sync release tags to Drupal.org Project
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          git remote add drupal-org '${{ secrets.DRUPAL_REPO_URL }}'
          git push drupal-org --tags
          git checkout master
          git push drupal-org master
